# Generated by Django 4.1 on 2022-10-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=models.TextField(null=True),
        ),
    ]
