# Generated by Django 4.1 on 2022-10-19 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.TimeField(default=datetime.time(14, 58, 10, 359554)),
        ),
    ]
