# Generated by Django 4.1 on 2022-10-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('comment', models.CharField(max_length=3000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('main_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_comment', to='blog.comments')),
            ],
            options={
                'verbose_name': 'Replies',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
