# Generated by Django 4.1 on 2022-10-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_replies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='comment',
            new_name='reply',
        ),
    ]
