# Generated by Django 4.1 on 2022-10-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='website',
        ),
    ]
